server:
  port: 8080
spring:
  profiles:
    active: local
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/webdemoone?serverTimezone=Asia/Shanghai&useUnicode=true&useSSL=false&characterEncoding=UTF-8
    username: root
    password: 123
    type: com.alibaba.druid.pool.DruidDataSource
  redis:
    host: 127.0.0.1
    port: 6379
    timeout: 5000
  aop:
    proxy-target-class: false
  kafka: #指定kafka 代理地址，可以多个
    bootstrap-servers: 192.168.1.125:9092,192.168.1.125:9093,192.168.1.125:9094
    producer: # 指定消息key和消息体的编解码方式
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer: # 指定消息key和消息体的编解码方式
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      enable-auto-commit: true
      auto-commit-interval: 1000
#mybatis:
#  mapper-locations: classpath:/mapper/*.xml #也可以使用spring.mvc.static-path-pattern: /resources/**
logging:
  path: /log/
  file: webdemoone.log
  level:
    com.redis.test: debug
elasticsearch:
  url: 192.168.1.125:9200
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
